language: python
python: "2.7"
install: "pip install -r requirements.txt"

before_script:
    - wget http://googleappengine.googlecode.com/files/google_appengine_1.8.8.zip -nv
    - unzip -q google_appengine_1.8.8.zip
    -export PATH="$PATH:google_appengine"
    -export GAE_SDK="google_appengine"

script: "python test/testloader.py"